### ISSUE TITLE
Memory Leak on pm2

### ISSUE THREAD

**Issue by NicolasBrondin** [apify/proxy-chain#45]
Hi !

I mounted the simplest instance of proxy-chain on an Amazon EC2 instance running with pm2, but when I came back today I found the proxy was down due to a memory leak with this error:

`(node:26700) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit`

Do you have any idea of what is happening ?

Thanks !

**Comment by mnmkng** [comment]
Hi @NicolasBrondin, thanks for reporting this.

The message you are seeing is not an actual error, but a warning message that a memory leak may be present in the system (caused by repeatedly attaching event listeners to a given `EventEmitter`). This may be a cause for concern, but more often than not, it's just a harmless warning.

With that being said, your process must have died for other reasons, because this warning does not kill the process by itself. If you could provide more info on why and how the process died, we could find out if it were a `proxy-chain` related issue.

**Comment by NicolasBrondin** [comment]
Thank you for your answer, and you're right the real issue was hidden by all the warning, this is the log of the exceptions thrown by the proxy:

`TypeError: Cannot read property '_httpMessage' of null
    at ServerResponse.detachSocket (_http_server.js:217:17)
    at HandlerTunnelDirect.onTrgSocketConnect (/home/ubuntu/proxy/node_modules/proxy-chain/build/handler_tunnel_direct.js:67:30)
    at Object.onceWrapper (events.js:291:20)
    at Socket.emit (events.js:203:13)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1042:10)
(node:1436) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:566:17)
    at ServerResponse.write (_http_outgoing.js:561:10)
    at IncomingMessage.ondata (_stream_readable.js:713:22)
    at IncomingMessage.emit (events.js:203:13)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:977:34)
    at ServerResponse.pipeOnDrainFunctionResult (_stream_readable.js:781:7)
    at ServerResponse.emit (events.js:203:13)
    at Socket.ondrain (internal/http.js:32:44)
    at Socket.emit (events.js:208:15)
    at onwriteDrain (_stream_writable.js:493:12)
    at afterWrite (_stream_writable.js:481:5)
    at onwrite (_stream_writable.js:474:7)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:10)
`

**Comment by jancurn** [comment]
You're right, this is related to issue https://github.com/apifytech/proxy-chain/issues/27, we plan to fix this. PRs are welcome :)

**Comment by jancurn** [comment]
The issue https://github.com/apifytech/proxy-chain/issues/27 has been fixed in the latest release, please can you try it again?

**Comment by mrsergeysh** [comment]
Still happening. @NicolasBrondin have you managed to solve this?

**Comment by NicolasBrondin** [comment]
No sorry, I switched to a turnkey solution for proxy as a solution !

**Comment by jancurn** [comment]
Should be fixed in https://github.com/apify/proxy-chain/pull/146, reopen if the issue persists
